### ISSUE TITLE
Multiple exceptions raised when running `docker-compose up`

### ISSUE THREAD

**Issue by metmajer** [ewolff/microservice#8] opened 2016-02-07 11:34 UTC
Thanks, @ewolff for providing this sample application. I am eager to learn from it and experiment with it.

I have built the application through a `mvn clean package` in `microservice-demo` and then ran `docker-compose up` in `docker`. During bootstrapping, a number of exceptions are being raised. It seems like discovery does not work.

Please see the entire [log file here](https://gist.github.com/metmajer/df2e13641a8cab7baecf).

**Comment by ewolff** [comment] 2016-09-29 09:03
I regularly use the demo and don't have any problems. You might need to wait for a while until the demo actually responds. Hope this helps!

**Comment by ewolff** [comment] 2016-09-29 09:18
I'll close it as I cannot reproduce it. Please reopen if needed.

**Closed by ewolff** 2016-09-29 09:18 UTC
